name: Deploy to GitHub pages

on:
  # trigger deployment on every push to main branch
  push:
    branches: [main]
    # trigger deployment manually
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Generate static vuepress files
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: |
        ls -a,
        cd Documentation,
        ls -a
